#!/bin/bash

commit_msg="$1"

# Define the regex pattern for the commit message format
commit_regex='^(majr|conf|docs|perf|fix|rtn|feat|patch|bug):(done|indev|blocked):[a-zA-Z0-9].+'

# Check if the commit message matches the pattern
if [[ "$commit_msg" =~ $commit_regex ]]; then
    echo "Commit message is valid."
    exit 0  # Exit with success status
else
    echo "Invalid commit message format. Please follow the pattern: type:status:message"
    exit 1  # Exit with error status
fi
