#!/bin/bash

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

echo $commit_msg
# Define the regex pattern for the commit message format
commit_regex='^(majr|conf|docs|perf|fix|rtn|feat|patch|bug):(done|indev|blocked):.+$'

# Check if the commit message matches the pattern
if [[ "$commit_msg" =~ $commit_regex ]]; then
    echo "Commit message is valid."
    exit 0  # Exit with success status
else
    echo "Invalid commit message format. Please follow the pattern: type:status:message"
    exit 1  # Exit with error status
fi
